version: '3'

services:
  front_end:
    image: sustainml:v0.1.0
    container_name: front_end
    environment:
      - node=orchestrator
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host

  app_requirements:
    image: sustainml:v0.1.0
    container_name: app_requirements
    environment:
      - node=app_requirements
    network_mode: host
    ipc: host

  carbon_tracker:
    image: sustainml:v0.1.0
    container_name: carbon_tracker
    environment:
      - node=carbon_tracker
    network_mode: host
    ipc: host

  hw_constraints:
    image: sustainml:v0.1.0
    container_name: hw_constraints
    environment:
      - node=hw_constraints
    network_mode: host
    ipc: host

  hw_resources:
    image: sustainml:v0.1.0
    container_name: hw_resources
    environment:
      - node=hw_resources
    network_mode: host
    ipc: host

  ml_model:
    image: sustainml:v0.1.0
    container_name: ml_model
    environment:
      - node=ml_model
    network_mode: host
    ipc: host

  ml_model_metadata:
    image: sustainml:v0.1.0
    container_name: ml_model_metadata
    environment:
      - node=ml_model_metadata
    network_mode: host
    ipc: host
