.pragma library

// Countries of sustainml-wp3/carbon_intensities.csv (latest yearly grid carbon intensity from
// Our World in Data), grouped by continent as [name, ISO alpha-2 code].
// The carbon footprint node looks the intensity up by the code.

var countries = {
    "Africa": [
        [
            "Algeria",
            "DZ"
        ],
        [
            "Angola",
            "AO"
        ],
        [
            "Benin",
            "BJ"
        ],
        [
            "Botswana",
            "BW"
        ],
        [
            "Burkina Faso",
            "BF"
        ],
        [
            "Burundi",
            "BI"
        ],
        [
            "Cameroon",
            "CM"
        ],
        [
            "Cape Verde",
            "CV"
        ],
        [
            "Central African Republic",
            "CF"
        ],
        [
            "Chad",
            "TD"
        ],
        [
            "Comoros",
            "KM"
        ],
        [
            "Congo",
            "CG"
        ],
        [
            "Cote d'Ivoire",
            "CI"
        ],
        [
            "Democratic Republic of Congo",
            "CD"
        ],
        [
            "Djibouti",
            "DJ"
        ],
        [
            "Egypt",
            "EG"
        ],
        [
            "Equatorial Guinea",
            "GQ"
        ],
        [
            "Eritrea",
            "ER"
        ],
        [
            "Eswatini",
            "SZ"
        ],
        [
            "Ethiopia",
            "ET"
        ],
        [
            "Gabon",
            "GA"
        ],
        [
            "Gambia",
            "GM"
        ],
        [
            "Ghana",
            "GH"
        ],
        [
            "Guinea",
            "GN"
        ],
        [
            "Guinea-Bissau",
            "GW"
        ],
        [
            "Kenya",
            "KE"
        ],
        [
            "Lesotho",
            "LS"
        ],
        [
            "Liberia",
            "LR"
        ],
        [
            "Libya",
            "LY"
        ],
        [
            "Madagascar",
            "MG"
        ],
        [
            "Malawi",
            "MW"
        ],
        [
            "Mali",
            "ML"
        ],
        [
            "Mauritania",
            "MR"
        ],
        [
            "Mauritius",
            "MU"
        ],
        [
            "Morocco",
            "MA"
        ],
        [
            "Mozambique",
            "MZ"
        ],
        [
            "Namibia",
            "NA"
        ],
        [
            "Niger",
            "NE"
        ],
        [
            "Nigeria",
            "NG"
        ],
        [
            "Rwanda",
            "RW"
        ],
        [
            "Sao Tome and Principe",
            "ST"
        ],
        [
            "Senegal",
            "SN"
        ],
        [
            "Seychelles",
            "SC"
        ],
        [
            "Sierra Leone",
            "SL"
        ],
        [
            "Somalia",
            "SO"
        ],
        [
            "South Africa",
            "ZA"
        ],
        [
            "South Sudan",
            "SS"
        ],
        [
            "Sudan",
            "SD"
        ],
        [
            "Tanzania",
            "TZ"
        ],
        [
            "Togo",
            "TG"
        ],
        [
            "Tunisia",
            "TN"
        ],
        [
            "Uganda",
            "UG"
        ],
        [
            "Zambia",
            "ZM"
        ],
        [
            "Zimbabwe",
            "ZW"
        ]
    ],
    "Asia": [
        [
            "Afghanistan",
            "AF"
        ],
        [
            "Armenia",
            "AM"
        ],
        [
            "Azerbaijan",
            "AZ"
        ],
        [
            "Bahrain",
            "BH"
        ],
        [
            "Bangladesh",
            "BD"
        ],
        [
            "Bhutan",
            "BT"
        ],
        [
            "Brunei",
            "BN"
        ],
        [
            "Cambodia",
            "KH"
        ],
        [
            "China",
            "CN"
        ],
        [
            "Cyprus",
            "CY"
        ],
        [
            "East Timor",
            "TL"
        ],
        [
            "Georgia",
            "GE"
        ],
        [
            "India",
            "IN"
        ],
        [
            "Indonesia",
            "ID"
        ],
        [
            "Iran",
            "IR"
        ],
        [
            "Iraq",
            "IQ"
        ],
        [
            "Japan",
            "JP"
        ],
        [
            "Jordan",
            "JO"
        ],
        [
            "Kazakhstan",
            "KZ"
        ],
        [
            "Kuwait",
            "KW"
        ],
        [
            "Kyrgyzstan",
            "KG"
        ],
        [
            "Laos",
            "LA"
        ],
        [
            "Lebanon",
            "LB"
        ],
        [
            "Malaysia",
            "MY"
        ],
        [
            "Maldives",
            "MV"
        ],
        [
            "Mongolia",
            "MN"
        ],
        [
            "Myanmar",
            "MM"
        ],
        [
            "Nepal",
            "NP"
        ],
        [
            "North Korea",
            "KP"
        ],
        [
            "Oman",
            "OM"
        ],
        [
            "Pakistan",
            "PK"
        ],
        [
            "Palestine",
            "PS"
        ],
        [
            "Philippines",
            "PH"
        ],
        [
            "Qatar",
            "QA"
        ],
        [
            "Saudi Arabia",
            "SA"
        ],
        [
            "Singapore",
            "SG"
        ],
        [
            "South Korea",
            "KR"
        ],
        [
            "Sri Lanka",
            "LK"
        ],
        [
            "Syria",
            "SY"
        ],
        [
            "Tajikistan",
            "TJ"
        ],
        [
            "Thailand",
            "TH"
        ],
        [
            "Turkey",
            "TR"
        ],
        [
            "Turkmenistan",
            "TM"
        ],
        [
            "United Arab Emirates",
            "AE"
        ],
        [
            "Uzbekistan",
            "UZ"
        ],
        [
            "Vietnam",
            "VN"
        ],
        [
            "Yemen",
            "YE"
        ]
    ],
    "Europe": [
        [
            "Albania",
            "AL"
        ],
        [
            "Austria",
            "AT"
        ],
        [
            "Belarus",
            "BY"
        ],
        [
            "Belgium",
            "BE"
        ],
        [
            "Bosnia and Herzegovina",
            "BA"
        ],
        [
            "Bulgaria",
            "BG"
        ],
        [
            "Croatia",
            "HR"
        ],
        [
            "Czechia",
            "CZ"
        ],
        [
            "Denmark",
            "DK"
        ],
        [
            "Estonia",
            "EE"
        ],
        [
            "Finland",
            "FI"
        ],
        [
            "France",
            "FR"
        ],
        [
            "Germany",
            "DE"
        ],
        [
            "Greece",
            "GR"
        ],
        [
            "Hungary",
            "HU"
        ],
        [
            "Iceland",
            "IS"
        ],
        [
            "Ireland",
            "IE"
        ],
        [
            "Italy",
            "IT"
        ],
        [
            "Latvia",
            "LV"
        ],
        [
            "Lithuania",
            "LT"
        ],
        [
            "Luxembourg",
            "LU"
        ],
        [
            "Malta",
            "MT"
        ],
        [
            "Moldova",
            "MD"
        ],
        [
            "Montenegro",
            "ME"
        ],
        [
            "Netherlands",
            "NL"
        ],
        [
            "North Macedonia",
            "MK"
        ],
        [
            "Norway",
            "NO"
        ],
        [
            "Poland",
            "PL"
        ],
        [
            "Portugal",
            "PT"
        ],
        [
            "Romania",
            "RO"
        ],
        [
            "Russia",
            "RU"
        ],
        [
            "Serbia",
            "RS"
        ],
        [
            "Slovakia",
            "SK"
        ],
        [
            "Slovenia",
            "SI"
        ],
        [
            "Spain",
            "ES"
        ],
        [
            "Sweden",
            "SE"
        ],
        [
            "Switzerland",
            "CH"
        ],
        [
            "Ukraine",
            "UA"
        ],
        [
            "United Kingdom",
            "GB"
        ]
    ],
    "North America": [
        [
            "Antigua and Barbuda",
            "AG"
        ],
        [
            "Bahamas",
            "BS"
        ],
        [
            "Barbados",
            "BB"
        ],
        [
            "Belize",
            "BZ"
        ],
        [
            "Canada",
            "CA"
        ],
        [
            "Costa Rica",
            "CR"
        ],
        [
            "Cuba",
            "CU"
        ],
        [
            "Dominica",
            "DM"
        ],
        [
            "Dominican Republic",
            "DO"
        ],
        [
            "El Salvador",
            "SV"
        ],
        [
            "Grenada",
            "GD"
        ],
        [
            "Guatemala",
            "GT"
        ],
        [
            "Haiti",
            "HT"
        ],
        [
            "Honduras",
            "HN"
        ],
        [
            "Jamaica",
            "JM"
        ],
        [
            "Mexico",
            "MX"
        ],
        [
            "Nicaragua",
            "NI"
        ],
        [
            "Panama",
            "PA"
        ],
        [
            "Saint Kitts and Nevis",
            "KN"
        ],
        [
            "Saint Lucia",
            "LC"
        ],
        [
            "Saint Vincent and the Grenadines",
            "VC"
        ],
        [
            "Trinidad and Tobago",
            "TT"
        ],
        [
            "United States",
            "US"
        ]
    ],
    "South America": [
        [
            "Argentina",
            "AR"
        ],
        [
            "Bolivia",
            "BO"
        ],
        [
            "Brazil",
            "BR"
        ],
        [
            "Chile",
            "CL"
        ],
        [
            "Colombia",
            "CO"
        ],
        [
            "Ecuador",
            "EC"
        ],
        [
            "Guyana",
            "GY"
        ],
        [
            "Paraguay",
            "PY"
        ],
        [
            "Peru",
            "PE"
        ],
        [
            "Suriname",
            "SR"
        ],
        [
            "Uruguay",
            "UY"
        ],
        [
            "Venezuela",
            "VE"
        ]
    ],
    "Oceania": [
        [
            "Australia",
            "AU"
        ],
        [
            "Fiji",
            "FJ"
        ],
        [
            "Kiribati",
            "KI"
        ],
        [
            "Nauru",
            "NR"
        ],
        [
            "New Zealand",
            "NZ"
        ],
        [
            "Papua New Guinea",
            "PG"
        ],
        [
            "Samoa",
            "WS"
        ],
        [
            "Solomon Islands",
            "SB"
        ],
        [
            "Tonga",
            "TO"
        ],
        [
            "Vanuatu",
            "VU"
        ]
    ]
}

var continents = Object.keys(countries)

function names(continent)
{
    return (countries[continent] || []).map(function(c) { return c[0] })
}

function code(continent, name)
{
    var list = countries[continent] || []
    for (var i = 0; i < list.length; i++)
        if (list[i][0] === name)
            return list[i][1]
    return ""
}

function name(continent, code)
{
    var list = countries[continent] || []
    for (var i = 0; i < list.length; i++)
        if (list[i][1] === code)
            return list[i][0]
    return ""
}
